# Node pinned as per original project
FROM node:18.7-alpine
ENV APP_DIR=/app
WORKDIR ${APP_DIR}
# Upgrade apk packages now
RUN apk --no-cache upgrade
# Also upgrade them whenever a consuming is built
ONBUILD RUN apk --no-cache upgrade
