FROM nginxinc/nginx-unprivileged:alpine

ENV APP_DIR=/app

ARG BUILD_DATE
ARG BUILD_VERSION
LABEL BUILD_DATE=${BUILD_DATE}
LABEL BUILD_VERSION=${BUILD_VERSION}

COPY nginx.conf /etc/nginx/nginx.conf
RUN rm -f /etc/nginx/conf.d/*.conf
COPY --chown=nginx:nginx sites-enabled.conf /etc/nginx/conf.d/sites-enabled.conf
COPY --chown=nginx:nginx app-frontend.conf /etc/nginx/sites-enabled/app.conf
COPY configure-nginx.sh /docker-entrypoint.d/10-configure-nginx.sh

EXPOSE 8080
