# Node pinned as per original project
FROM node:iron-alpine
ENV APP_DIR=/app
WORKDIR ${APP_DIR}
# Upgrade apk packages now
RUN apk --no-cache upgrade
# Also upgrade them whenever a consuming is built
ONBUILD RUN apk --no-cache upgrade
ONBUILD COPY package.json package-lock.json ./
ONBUILD RUN npm ci
