# Python pinned as per original project
FROM python:3.9-alpine

ENV APP_DIR=/app
ENV DEP_PYUWSGI_VERSION=2.0.22

ARG BUILD_DATE
ARG BUILD_VERSION
LABEL BUILD_DATE=${BUILD_DATE}
LABEL BUILD_VERSION=${BUILD_VERSION}

WORKDIR ${APP_DIR}
RUN addgroup -S uwsgi && adduser -S -H -G uwsgi uwsgi && \
    python3 -m venv /app/venv && \
    /app/venv/bin/pip3 install --no-cache-dir --upgrade pip pyuwsgi==${DEP_PYUWSGI_VERSION}

CMD ["/app/venv/bin/uwsgi", "--http-socket", ":8888", "--master", "-w", "application:application"]
EXPOSE 8888

ONBUILD ARG release_name
ONBUILD COPY requirements.txt ${APP_DIR}
ONBUILD RUN echo ${release_name} > ${APP_DIR}/version_label && \
            apk upgrade && apk add build-base curl git libffi libffi-dev openssl-dev && rm -rf /var/cache/apk && \
            /app/venv/bin/pip3 install --no-cache-dir --upgrade pip -r requirements.txt && \
            apk del build-base libffi-dev openssl-dev && rm -rf /root/.cache
ONBUILD COPY --chown=uwsgi:uwsgi . ${APP_DIR}
ONBUILD USER uwsgi
